sudo: required
services:
  - docker


before_install:
  - docker build -t raheel87/docker-react -f Dockerfile.dev .

script:
  - docker run raheel87/docker-react npm run test -- --coverage

deploy:
  provider:elasticbeanstalk
  region: "us-west-2"
  app:docker
  env:"Docker-env"
